[package]
name = "siar-event-log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
siar-domain = { path = "../siar-domain" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
blake3.workspace = true
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true
