[package]
name = "siar-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
siar-domain.workspace = true
siar-identity-multidevice.workspace = true
ed25519-dalek.workspace = true
x25519-dalek.workspace = true
chacha20poly1305.workspace = true
rand_core.workspace = true
blake3.workspace = true
zeroize.workspace = true
serde.workspace = true
thiserror.workspace = true
bytes.workspace = true

[dev-dependencies]
postcard.workspace = true
